[package]
name = "kernels"
version.workspace = true
edition.workspace = true
license = "MIT OR Apache-2.0"

[features]
default = []
bazel_build = []

# Specific kernels
bridge = []
dumb = []
wallet = []
miner = []
nockchain_peek = []

[dependencies]
