[package]
name = "murmur3"
version = "0.5.2"
authors = ["Stu Small <stuart.alan.small@gmail.com>"]
description = "A rust implementation of Murmur3 hash"
repository = "https://github.com/stusmall/murmur3"
keywords = ["hash", "murmur3", "murmur"]
license = "MIT/Apache-2.0"
edition = "2021"

[features]
default = []
c-ffi = ["murmur3-sys"]

[dependencies]
murmur3-sys = { path = "./murmur3-sys", optional = true }

[dev-dependencies]
quickcheck = "1.0.3"
